
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: echo-server
    image: mykhailomaidan/echo-server
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 20
      failureThreshold: 3

