apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
spec:
  containers:
  - name: echo-server
    image: mykhailomaidan/echo-server
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 200m
        memory: 4Gi
      limits:
        cpu: 200m
        memory: 5Gi
